apiVersion: argoproj.io/v1alpha1
kind: EventSource
metadata:
  name: webhook
spec:
  service:
    ports:
      - port: 12345
        targetPort: 12345
  webhook:
    test-messaging:
      port: "12345"
      endpoint: /test
      method: POST